name: First workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: afficher bonjour
        run: echo "Salut"
      - name: dire good luck
        run: echo "Bonne chance"

